package entity;
// Generated Jun 20, 2020 5:44:52 PM by Hibernate Tools 4.3.1



/**
 * ApplicationFormId generated by hbm2java
 */
public class ApplicationFormId  implements java.io.Serializable {


     private int mssv;
     private int reExamId;

    public ApplicationFormId() {
    }

    public ApplicationFormId(int mssv, int reExamId) {
       this.mssv = mssv;
       this.reExamId = reExamId;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public int getReExamId() {
        return this.reExamId;
    }
    
    public void setReExamId(int reExamId) {
        this.reExamId = reExamId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ApplicationFormId) ) return false;
		 ApplicationFormId castOther = ( ApplicationFormId ) other; 
         
		 return (this.getMssv()==castOther.getMssv())
 && (this.getReExamId()==castOther.getReExamId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMssv();
         result = 37 * result + this.getReExamId();
         return result;
   }   


}


