package entity;
// Generated Jun 20, 2020 11:24:38 AM by Hibernate Tools 4.3.1



/**
 * ApplicationForm generated by hbm2java
 */
public class ApplicationForm  implements java.io.Serializable {


     private Integer id;
     private ReExamination reExamination;
     private Student student;
     private int reExamId;
     private String hoTen;
     private String monPhucKhao;
     private String cotDiemPhucKhao;
     private String diemMongMuon;
     private String lyDo;
     private Byte trangThai;

    public ApplicationForm() {
    }

	
    public ApplicationForm(Student student, int reExamId, String hoTen, String monPhucKhao, String cotDiemPhucKhao, String diemMongMuon, String lyDo) {
        this.student = student;
        this.reExamId = reExamId;
        this.hoTen = hoTen;
        this.monPhucKhao = monPhucKhao;
        this.cotDiemPhucKhao = cotDiemPhucKhao;
        this.diemMongMuon = diemMongMuon;
        this.lyDo = lyDo;
    }
    public ApplicationForm(ReExamination reExamination, Student student, int reExamId, String hoTen, String monPhucKhao, String cotDiemPhucKhao, String diemMongMuon, String lyDo, Byte trangThai) {
       this.reExamination = reExamination;
       this.student = student;
       this.reExamId = reExamId;
       this.hoTen = hoTen;
       this.monPhucKhao = monPhucKhao;
       this.cotDiemPhucKhao = cotDiemPhucKhao;
       this.diemMongMuon = diemMongMuon;
       this.lyDo = lyDo;
       this.trangThai = trangThai;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ReExamination getReExamination() {
        return this.reExamination;
    }
    
    public void setReExamination(ReExamination reExamination) {
        this.reExamination = reExamination;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public int getReExamId() {
        return this.reExamId;
    }
    
    public void setReExamId(int reExamId) {
        this.reExamId = reExamId;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getMonPhucKhao() {
        return this.monPhucKhao;
    }
    
    public void setMonPhucKhao(String monPhucKhao) {
        this.monPhucKhao = monPhucKhao;
    }
    public String getCotDiemPhucKhao() {
        return this.cotDiemPhucKhao;
    }
    
    public void setCotDiemPhucKhao(String cotDiemPhucKhao) {
        this.cotDiemPhucKhao = cotDiemPhucKhao;
    }
    public String getDiemMongMuon() {
        return this.diemMongMuon;
    }
    
    public void setDiemMongMuon(String diemMongMuon) {
        this.diemMongMuon = diemMongMuon;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }

    public Byte getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Byte trangThai) {
        this.trangThai = trangThai;
    }


}


