package entity;
// Generated Jun 17, 2020 3:46:42 PM by Hibernate Tools 4.3.1



/**
 * CourseStudent generated by hbm2java
 */
public class CourseStudent  implements java.io.Serializable {


     private int id;
     private String maMon;
     private Integer mssv;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float diemTong;

    public CourseStudent() {
    }

	
    public CourseStudent(int id) {
        this.id = id;
    }
    public CourseStudent(int id, String maMon, Integer mssv, Float diemGk, Float diemCk, Float diemKhac, Float diemTong) {
       this.id = id;
       this.maMon = maMon;
       this.mssv = mssv;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public Integer getMssv() {
        return this.mssv;
    }
    
    public void setMssv(Integer mssv) {
        this.mssv = mssv;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(Float diemTong) {
        this.diemTong = diemTong;
    }




}


