package entity;
// Generated Jun 20, 2020 5:44:52 PM by Hibernate Tools 4.3.1



/**
 * CourseStudentId generated by hbm2java
 */
public class CourseStudentId  implements java.io.Serializable {


     private String maMon;
     private int mssv;

    public CourseStudentId() {
    }

    public CourseStudentId(String maMon, int mssv) {
       this.maMon = maMon;
       this.mssv = mssv;
    }
   
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CourseStudentId) ) return false;
		 CourseStudentId castOther = ( CourseStudentId ) other; 
         
		 return ( (this.getMaMon()==castOther.getMaMon()) || ( this.getMaMon()!=null && castOther.getMaMon()!=null && this.getMaMon().equals(castOther.getMaMon()) ) )
 && (this.getMssv()==castOther.getMssv());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaMon() == null ? 0 : this.getMaMon().hashCode() );
         result = 37 * result + this.getMssv();
         return result;
   }   


}


