package entity;
// Generated Jun 17, 2020 3:46:42 PM by Hibernate Tools 4.3.1



/**
 * CourseStudent generated by hbm2java
 */

public class CourseStudent  implements java.io.Serializable {

     private IdCourseStudent ics;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float diemTong;

    public CourseStudent() {
    }

	
    public CourseStudent( IdCourseStudent ics,Float diemGk, Float diemCk, Float diemKhac, Float diemTong) {
       this.ics = ics;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
    
    public IdCourseStudent getIcs() {
        return this.ics;
    }
    
    public void setIcs(IdCourseStudent ics) {
        this.ics = ics;
    }
    
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(Float diemTong) {
        this.diemTong = diemTong;
    }
}


