package entity;
// Generated Jun 20, 2020 11:24:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String maMon;
     private String tenMon;
     private String phongHoc;
     private String lop;
     private Set courseStudents = new HashSet(0);

    public Course() {
    }

	
    public Course(String maMon, String tenMon, String phongHoc, String lop) {
        this.maMon = maMon;
        this.tenMon = tenMon;
        this.phongHoc = phongHoc;
        this.lop = lop;
    }
    public Course(String maMon, String tenMon, String phongHoc, String lop, Set courseStudents) {
       this.maMon = maMon;
       this.tenMon = tenMon;
       this.phongHoc = phongHoc;
       this.lop = lop;
       this.courseStudents = courseStudents;
    }
   
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public String getTenMon() {
        return this.tenMon;
    }
    
    public void setTenMon(String tenMon) {
        this.tenMon = tenMon;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }
    public Set getCourseStudents() {
        return this.courseStudents;
    }
    
    public void setCourseStudents(Set courseStudents) {
        this.courseStudents = courseStudents;
    }




}


