package entity;
// Generated Jun 20, 2020 11:24:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReExamination generated by hbm2java
 */
public class ReExamination  implements java.io.Serializable {


     private Integer id;
     private Date ngayBatDau;
     private Date ngayKetThuc;
     private Set applicationForms = new HashSet(0);

    public ReExamination() {
    }

	
    public ReExamination(Date ngayBatDau, Date ngayKetThuc) {
        this.ngayBatDau = ngayBatDau;
        this.ngayKetThuc = ngayKetThuc;
    }
    public ReExamination(Date ngayBatDau, Date ngayKetThuc, Set applicationForms) {
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
       this.applicationForms = applicationForms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }
    public Set getApplicationForms() {
        return this.applicationForms;
    }
    
    public void setApplicationForms(Set applicationForms) {
        this.applicationForms = applicationForms;
    }




}


