package entity;
// Generated Jun 20, 2020 5:44:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int mssv;
     private String hoTen;
     private String gioiTinh;
     private String cmnd;
     private String lop;
     private Set courseStudents = new HashSet(0);
     private Set applicationForms = new HashSet(0);

    public Student() {
    }

	
    public Student(int mssv, String hoTen, String gioiTinh, String cmnd, String lop) {
        this.mssv = mssv;
        this.hoTen = hoTen;
        this.gioiTinh = gioiTinh;
        this.cmnd = cmnd;
        this.lop = lop;
    }
    public Student(int mssv, String hoTen, String gioiTinh, String cmnd, String lop, Set courseStudents, Set applicationForms) {
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
       this.lop = lop;
       this.courseStudents = courseStudents;
       this.applicationForms = applicationForms;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }
    public Set getCourseStudents() {
        return this.courseStudents;
    }
    
    public void setCourseStudents(Set courseStudents) {
        this.courseStudents = courseStudents;
    }
    public Set getApplicationForms() {
        return this.applicationForms;
    }
    
    public void setApplicationForms(Set applicationForms) {
        this.applicationForms = applicationForms;
    }




}


