package entity;
// Generated Jun 17, 2020 3:46:42 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String userName;
     private String password;
     private Byte isAdmin;

    public User() {
    }

	
    public User(int id, String userName, String password) {
        this.id = id;
        this.userName = userName;
        this.password = password;
    }
    public User(int id, String userName, String password, Byte isAdmin) {
       this.id = id;
       this.userName = userName;
       this.password = password;
       this.isAdmin = isAdmin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }




}


